set -g mouse on # Mouse input
set -g renumber-windows on # Renumber windows when one is closed
set -g set-titles on # Window title

# Avoids waiting for a keychain when esc is pressed
set -g escape-time 0

# Right status line
set -g status-right "#(whoami)@#(hostname -s)" # user@hostname
